theme: jekyll-theme-minimal
title: Slava I. Maslennikov
logo: me.jpg
description: Cool Consulting, LLC
author: Slava I. Maslennikov

defaults:
  - scope:
      path: "/"
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post

permalink: /posts/:title/