---
- name: Create wheel group
  group:
    name: wheel
    state: present

- name: Create slava user
  user:
    name: slava
    comment: "Slava Maslennikov"
    groups: wheel
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_type: rsa
    ssh_key_file: .ssh/id_rsa
    ssh_key_passphrase: "{{ ssh_key_passphrase }}"
    password: "{{ vps_slava_password }}"

- name: Add our pubkeys
  authorized_key:
    user: slava
    state: present
    key: https://github.com/smaslennikov.keys

- name: Allow %wheel sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'

- name: Add user to GPIO groups
  user:
    name: slava
    groups: gpio,i2c
    append: yes
  when: gpio_hosts is search(inventory_hostname)
